### ISSUE TITLE
Now Playing Feature

### ISSUE THREAD

**Issue by dwebster17** [dwebster17/Spinn#8]

**Comment by mfeniseycopes** [comment]
### Styling
- [ ] I would like to see info about the current track in the player bar (track name, artist, where we are in the song, etc.)
- [ ] Let's try to get the play buttons a little bit closer to Spotify's styling

### Bug-free nav
- [ ] Its a little counter-intuitive when I click the 'Play' button on a playlist, but it's just a link

### Adequate seeds
- Good for now!
